[[links]]
key = "alan"
url = "https://love.alan.com/tezolapu"

[[links]]
key = "comet"
url = "https://vrlps.co/HJnRn_DrM/cp"

[[links]]
key = "compta"
url = "https://www.dougs.fr/?r=ykmHYYbtKM"

[[links]]
key = "jetbrains"
url = "https://www.jetbrains.com/?from=Amazon%20Alternatives"

[[links]]
key = "qonto"
url = "https://qonto.com/r/gs21bf"

[[links]]
key = "revolut"
url = "https://revolut.com/referral/tombucn"
